image: quay.io/dennybaa/diffy-onbuild:latest
env:
  - DRONE_EXPOSED=world
script:
  - echo "Hello $DRONE_EXPOSED"
  - echo "----"
  - cat  /hello
  - which socat || true
  - ps -A uxw
services:
  - quay.io/dennybaa/diffy-onbuild:latest
